Use jq instead of `deno eval` in CI [take 2]
lowlighter/libs pull request #69
Opened 2024-07-06 20:49 UTC by lishaduck

Try to reland #68

2024-07-06 20:50 UTC, lishaduck commented
I'm not really sure how to test this. Should we make CI pipelines run on edit?

2024-07-06 20:58 UTC, lishaduck commented
Oh, I see. It's running via pull_request_trigger, so it doesn't run my workflow for security reasons. I'd forgotten about that. I'll trigger the edge cases on my repo and report back.

2024-07-06 21:09 UTC, lishaduck commented
Not quite. I've got a few more ideas up my sleeve.

2024-07-06 21:21 UTC, lishaduck commented
Yeah! It works!

2024-07-06 21:41 UTC, lishaduck commented
> `deno task dev` is running over the `dom` package, which doesn't have a deno.json. Is that intended?

I see. It's not going to be triggered for that. Ok, it works then!
I also "explicitly" set pipefail, etc so that that won't be an issue in the future. (though bash is weird, and think it won't actually help with interpolation, per [oils](https://www.oilshell.org/release/latest/doc/error-handling.html#bash:~:text=%23%20Shell%20style-,x%3D%24(false),-sigpipe_status_ok%20Ignores%20an), which flagged this in some of my scripts)

2024-07-07 00:53 UTC, lowlighter commented
The dom package should be excluded now (I renamed it temporarly to `deno.json` instead of `deno.jsonc` to skip for now). 
It's indeed a WIP

Sorry I didn't see your PR I made some changes in the meantime to the CI by moving some stuff around to improve linting and testing.

If you have time, could you rebase your changes on main branch and reapply your changes ? (there's also one more deno.eval to patch in the linting job)

Btw is there any reason to explicitely add `shell: bash` to all jobs ? 
It kind of feel too verbose but if there's a catch with the implicit way, why not

2024-07-07 01:53 UTC, lishaduck commented
> The dom package should be excluded now (I renamed it temporarly to `deno.json` instead of `deno.jsonc` to skip for now). It's indeed a WIP

Thanks for letting me know 😁 I was manually running it and it failed.

> Sorry I didn't see your PR I made some changes in the meantime to the CI by moving some stuff around to improve linting and testing.
>
> If you have time, could you rebase your changes on main branch and reapply your changes ? (there's also one more deno.eval to patch in the linting job)

That's fine, can do!
 
> Btw is there any reason to explicitely add `shell: bash` to all jobs ? It kind of feel too verbose but if there's a catch with the implicit way, why not

I agree it feels too verbose, but it does a few things:
1. It runs with `-o pipefail`, so that failing commands correctly fail the pipeline (main reason)
2. On Windows, it runs it on git bash, so that the syntax is still valid (good reason)
3. It makes it use bash on self-hosted runners that default to POSIX sh (and runs with `--noprofile --norc` so that it's fully reproducible, and faster) (ok reason)

`#3` doesn't apply to this, but if you decided to run tests on windows, `2` makes it trivial (at least, the CI part). `1` is definitely a win.

2024-07-07 02:18 UTC, lishaduck commented
Ok, I think it should be good to go now!

2024-07-07 02:37 UTC, lowlighter approved these changes

2024-07-07 02:43 UTC, lowlighter commented
Acutally looking at the GA docs, it seems it's possible to specify default shell/working-directory
https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#setting-default-shell-and-working-directory

It might be better to set it once per job rather than at every step
Seems like it could help cleaning the `working-directory` mostly everywhere too

2024-07-07 02:46 UTC, lishaduck commented
> Actually looking at the GA docs, it seems it's possible to specify the default shell globally https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#setting-default-shell-and-working-directory
> 
> It might be better to set it once per job rather than at every step
> 
> Seems like it's also possible to specifify the default `working-directory` per a job basis: https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#example-setting-default-run-step-options-for-a-job Could help for some cleanup too

Ok, I can clean that up!

2024-07-07 05:47 UTC, lowlighter requested changes

2024-07-07 05:47 UTC, lowlighter commented on .github/workflows/ci_package.yml
> +        shell: bash
```suggestion
        working-directory: ${{ inputs.package }}
```

2024-07-07 05:47 UTC, lowlighter commented on .github/workflows/ci_package.yml
> +        shell: bash
unecessary

2024-07-07 05:47 UTC, lowlighter commented on .github/workflows/ci_package.yml
> +        shell: bash
```suggestion
        working-directory: ${{ inputs.package }}
```

2024-07-07 05:47 UTC, lowlighter commented on .github/workflows/ci_package.yml
> +        shell: bash
```suggestion
        working-directory: ${{ inputs.package }}
```

2024-07-07 15:28 UTC, lishaduck commented
Oh, I guess my comment didn't get posted. I got some sleep, but I'm off to fix all those.

2024-07-07 17:37 UTC, lishaduck commented
It works now, and is fully cleaned up! Thanks for your patience, it's been a while since I've JQed.
One thing I noticed is that you don't actually support saving comments in your config syncer, so it might be more unambiguous to use `deno.json` instead? Comments would break jq, though hopefully that'll change soon.

2024-07-09 19:45 UTC, lishaduck commented
@lowlighter, ping :)

2024-07-10 01:14 UTC, lowlighter approved these changes

2024-07-10 01:15 UTC, merged

2024-07-10 01:40 UTC, lowlighter commented
Seems to work great, thanks !

> One thing I noticed is that you don't actually support saving comments in your config syncer, so it might be more unambiguous to use `deno.json` instead? Comments would break jq, though hopefully that'll change soon ([jqlang/jq#2548](https://github.com/jqlang/jq/pull/2548) is held up on rebasing, etc, but is relatively likely to merge _someday_).

Yeah, but it's mostly because the JSONC library from deno/std doesn't support it, it's not really that I don't want to x)

2024-07-10 01:46 UTC, lishaduck commented
> Seems to work great, thanks !

You're welcome!

> > One thing I noticed is that you don't actually support saving comments in your config syncer, so it might be more unambiguous to use `deno.json` instead? Comments would break jq, though hopefully that'll change soon ([jqlang/jq#2548](https://github.com/jqlang/jq/pull/2548) is held up on rebasing, etc, but is relatively likely to merge _someday_).
> 
> Yeah, but it's mostly because the JSONC library from deno/std doesn't support it, it's not really that I don't want to x)

Fair enough.